<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Basket_ItemRemoveButton</name>
   <tag></tag>
   <elementGuidId>9941ff89-9fc1-48da-aaa3-6e0ebd04cf50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@id[contains(.,'remove')]]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@id[contains(.,'remove')]]</value>
   </webElementProperties>
</WebElementEntity>
