<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add_bskt-icon</name>
   <tag></tag>
   <elementGuidId>ffd69dea-9ebb-404e-b5c6-4e06fb9e3c5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dynamicDirective']/product-deck/section/div[2]/div[4]/div/div/div/div[2]/div/div/product-template/div/div[4]/div[3]/div/div[4]/div[4]/div[2]/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bskt-icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dynamicDirective&quot;)/product-deck[@class=&quot;ng-scope ng-isolate-scope&quot;]/section[@class=&quot;row custom-component product-deck sticky-parent&quot;]/div[@class=&quot;col-md-9 wid-fix clearfix pl-wrap&quot;]/div[@class=&quot;col-xs-12 product-deck-container pad-0&quot;]/div[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;tab-pane ng-scope active&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;items&quot;]/div[@class=&quot;item prod-deck row ng-scope&quot;]/product-template[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;col-sm-12 col-xs-12 add-bskt&quot;]/div[@class=&quot;elements&quot;]/div[@class=&quot;delivery-opt&quot;]/div[@class=&quot;col-xs-12 bskt-opt ng-scope&quot;]/div[@class=&quot;col-sm-5 col-xs-5 pad-0&quot;]/button[@class=&quot;btn btn-add col-xs-9&quot;]/span[@class=&quot;bskt-icon&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='dynamicDirective']/product-deck/section/div[2]/div[4]/div/div/div/div[2]/div/div/product-template/div/div[4]/div[3]/div/div[4]/div[4]/div[2]/button/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[1]/span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qty'])[2]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bb Royal'])[4]/preceding::span[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[4]/div[2]/button/span</value>
   </webElementXpaths>
</WebElementEntity>
