<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FundTheWallet_AmountToFund</name>
   <tag></tag>
   <elementGuidId>04ff26e3-1b37-4688-a46d-7e9bdc44a470</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='id_amount_to_fund']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='id_amount_to_fund']</value>
   </webElementProperties>
</WebElementEntity>
