<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FundThewallet_Btn_SUBMIT</name>
   <tag></tag>
   <elementGuidId>435dc063-fcfe-4a2f-af6f-246bf6df119d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@qa='submitMW']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@qa='submitMW']</value>
   </webElementProperties>
</WebElementEntity>
