<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Basket_SubtotalPerProductInBasket</name>
   <tag></tag>
   <elementGuidId>35a57c0a-a709-410e-9125-d3a31a2b3937</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@qa='subtotal']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@qa='subtotal']/span[2]</value>
   </webElementProperties>
</WebElementEntity>
