<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Basket_QuantityPerProductInBasket</name>
   <tag></tag>
   <elementGuidId>facdaf3c-b22f-4ed2-8b4f-ef516d6af071</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@class='text-change-qty-search-popup']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@class='text-change-qty-search-popup']</value>
   </webElementProperties>
</WebElementEntity>
