<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Basket_UnitPriceperProductinBasket</name>
   <tag></tag>
   <elementGuidId>57e7c66b-c6c0-4642-9f29-f065a87f058c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@qa='prodPrice']/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@qa='prodPrice']/input</value>
   </webElementProperties>
</WebElementEntity>
