<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Actions_Row1</name>
   <tag></tag>
   <elementGuidId>7fa7e6f2-6821-44b6-a9a3-eedac8156987</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//td[6]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td[6]/button[2]</value>
   </webElementProperties>
</WebElementEntity>
