<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Row1</name>
   <tag></tag>
   <elementGuidId>6f8817ee-9509-4258-8881-7c33e70830f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//td[6]/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td[6]/button[1]</value>
   </webElementProperties>
</WebElementEntity>
