<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tableRows_DueDate</name>
   <tag></tag>
   <elementGuidId>b7bc827a-334b-4d2d-89ad-397b6660ec89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tbody[@class='ant-table-tbody']/tr/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody[@class='ant-table-tbody']/tr/td[3]</value>
   </webElementProperties>
</WebElementEntity>
