<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tableHeaders_Invoices</name>
   <tag></tag>
   <elementGuidId>d346fb54-5191-47e0-96ca-f5e402b71d68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//thead/tr/th/span/div/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//thead/tr/th/span/div/span[1]</value>
   </webElementProperties>
</WebElementEntity>
