<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tableRows_AmountDueCurrencyType</name>
   <tag></tag>
   <elementGuidId>a9171019-f81e-4a1d-bff5-51bd112c7a5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tbody[@class='ant-table-tbody']/tr/td[5]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody[@class='ant-table-tbody']/tr/td[5]/span</value>
   </webElementProperties>
</WebElementEntity>
