<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tableRows_Status</name>
   <tag></tag>
   <elementGuidId>e15bb979-cf92-4587-8ace-8871efbd012e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tbody[@class='ant-table-tbody']/tr/td[4]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody[@class='ant-table-tbody']/tr/td[4]/div</value>
   </webElementProperties>
</WebElementEntity>
