<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OrderStatement_Item_Quantity</name>
   <tag></tag>
   <elementGuidId>5f10dac7-dc61-4d27-866f-40cc672ddb13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[@class='order-invoice-items']/tbody/tr/td[4][@qa='qtyINVOICE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[@class='order-invoice-items']/tbody/tr/td[4][@qa='qtyINVOICE']</value>
   </webElementProperties>
</WebElementEntity>
