<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OrderStatement_Item_ItemName</name>
   <tag></tag>
   <elementGuidId>78123354-f699-45bd-bebc-ec19e4bb64cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[@class='order-invoice-items']/tbody/tr/td[2]/div[@qa='brandprodNameINVOICE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[@class='order-invoice-items']/tbody/tr/td[2]/div[@qa='brandprodNameINVOICE']</value>
   </webElementProperties>
</WebElementEntity>
