<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_Title</name>
   <tag></tag>
   <elementGuidId>ea7ee0d1-5fb1-402a-870e-7bc5ad394024</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='tab-cards']/div/div[@class='ant-card-head']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='tab-cards']/div/div[@class='ant-card-head']/div/div</value>
   </webElementProperties>
</WebElementEntity>
