<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InvoicesHeading</name>
   <tag></tag>
   <elementGuidId>fc131fa7-c4e6-4506-a22e-1685090d36f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//h2[@class='ant-typography']/span[contains(text(),'Invoices')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h2[@class='ant-typography']/span[contains(text(),'Invoices')]</value>
   </webElementProperties>
</WebElementEntity>
