<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>List2_ProductName</name>
   <tag></tag>
   <elementGuidId>0d3ffa11-62c6-4a71-a40f-950e155fce29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[contains(@id,'product_fruitsvegetables')][@qa='product']/div[@qa='product_name']/span/a/span[@qa='prodNameRP']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[contains(@id,'product_fruitsvegetables')][@qa='product']/div[@qa='product_name']/span/a/span[@qa='prodNameRP']</value>
   </webElementProperties>
</WebElementEntity>
