<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MyShoppingLists_ShopFromYourList_ListName</name>
   <tag></tag>
   <elementGuidId>6045e13b-f819-4089-ab75-13c06480dde4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='list2_shoppingListName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='list2_shoppingListName']</value>
   </webElementProperties>
</WebElementEntity>
