<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OrderDetails_CopyToList_AddToExistingShoppingList_Btn_COPY</name>
   <tag></tag>
   <elementGuidId>207a8113-18c6-4d3e-9687-703e6b5b93ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div/span/a[contains(.,'COPY')][@qa='copyBtnSL']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div/span/a[contains(.,'COPY')][@qa='copyBtnSL']</value>
   </webElementProperties>
</WebElementEntity>
