<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PastOrders_Header_DeliveryDateTime</name>
   <tag></tag>
   <elementGuidId>058b18bd-6efc-4623-b688-246d210c1caa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dynamicDirective']/information/section/my-order-list/div/section/div[2]/div/div/div/my-order/div/div/div[contains(@class,'delivery-slot')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='dynamicDirective']/information/section/my-order-list/div/section/div[2]/div/div/div/my-order/div/div/a/span[contains(text(),'View ')][contains(text(),'Items')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>my-order flex flex-responsive border pointer bg-dbdbdb</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vm.toggleDropDown()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'bg-eee':vm.active,'bg-dbdbdb':!vm.active,'dim':vm.active &amp;&amp; !vm.showDropdown}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Delivered on 18 FEB, MON 5:00 PM - 7:30 PMOrder Amount: Rs 1360.1812 Items</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='dynamicDirective']/information/section/my-order-list/div/section/div[2]/div/div/div/my-order/div/div/div[contains(@class,'delivery-slot')]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='dynamicDirective']/information/section/my-order-list/div/section/div[2]/div/div[3]/div/my-order/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAST ORDERS'])[1]/following::div[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HELP'])[1]/following::div[8]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//my-order/div/div</value>
   </webElementXpaths>
</WebElementEntity>
