<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PastOrders_Header_DeliveryStatus</name>
   <tag></tag>
   <elementGuidId>dd513fe2-8ac1-4127-a184-6c7bc1ea856a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dynamicDirective']/information/section/my-order-list/div/section/div[2]/div/div/div/my-order/div/div/div[3]/span/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[(text() = 'Delivered on' or . = 'Delivered on')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!vm.cancelledOrder</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-scope</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delivered on</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dynamicDirective&quot;)/information[@class=&quot;ng-scope ng-isolate-scope&quot;]/section[@class=&quot;non-linear row custom-component&quot;]/my-order-list[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;my-order-page&quot;]/section[@class=&quot;row custom-component product-deck sticky-parent regular&quot;]/div[@class=&quot;col-md-9 wid-fix clearfix pl-wrap&quot;]/div[1]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;order-wrapper&quot;]/my-order[@class=&quot;ng-isolate-scope&quot;]/div[1]/div[@class=&quot;my-order flex flex-responsive border pointer bg-dbdbdb&quot;]/div[@class=&quot;flex flex-responsive ng-scope&quot;]/span[@class=&quot;bold clr-666666 font12&quot;]/span[@class=&quot;ng-scope&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='dynamicDirective']/information/section/my-order-list/div/section/div[2]/div/div[3]/div/my-order/div/div/div[3]/span/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAST ORDERS'])[1]/following::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HELP'])[1]/following::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Amount: Rs 1360.18'])[1]/preceding::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivered on'])[2]/preceding::span[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[3]/span/span</value>
   </webElementXpaths>
</WebElementEntity>
