<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ShopFromBasket_Alert_SelectAtleastOne</name>
   <tag></tag>
   <elementGuidId>7c2a1e65-17d9-4adc-930a-2e67bbdde799</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='alert-msg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='alert-msg']</value>
   </webElementProperties>
</WebElementEntity>
