<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ShopFromBasket_AllFruitsAndVegetableCount</name>
   <tag></tag>
   <elementGuidId>af5162f3-9abd-4996-b6b3-9a93a3e1ebff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div/ul/li[contains(@id,'product_fruitsvegetables')][@qa='product']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div/ul/li[contains(@id,'product_fruitsvegetables')][@qa='product']</value>
   </webElementProperties>
</WebElementEntity>
