<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ShopFromBasket_CheckBox_FruitsAndVegetables</name>
   <tag></tag>
   <elementGuidId>a734a037-66ea-4587-bab4-9c2c0a2fd668</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[contains(@id,'product_fruitsvegetables')][@qa='product']/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[contains(@id,'product_fruitsvegetables')][@qa='product']/div/label</value>
   </webElementProperties>
</WebElementEntity>
