<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WalletActivity_Row1Data</name>
   <tag></tag>
   <elementGuidId>4ab8d499-dd3f-45ce-836a-08f6bf447f30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[@class='uiv2-table']/tbody/tr[1]/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[@class='uiv2-table']/tbody/tr[1]/td</value>
   </webElementProperties>
</WebElementEntity>
