<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkout_DefaultDeliveryChargeRs30</name>
   <tag></tag>
   <elementGuidId>a951b3b1-5e54-42b3-8f2a-6a60ca9a6f5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@class='text-muted']/span/span/span[contains(.,'30')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@class='text-muted']/span/span/span[contains(.,'30')]</value>
   </webElementProperties>
</WebElementEntity>
