<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkout_OrderSummary_TotalAmountPayable</name>
   <tag></tag>
   <elementGuidId>6f63a3e6-b715-4585-b05f-72cd08c10152</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//td[@qa='totalAmtCKO']/strong[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td[@qa='totalAmtCKO']/strong[2]</value>
   </webElementProperties>
</WebElementEntity>
