<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkout_DefaultDeliverySlotTomorrow</name>
   <tag></tag>
   <elementGuidId>7cb73e6f-25f4-4da6-b4ff-df9706f2cb3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@qa='date1']/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@qa='date1']/h4</value>
   </webElementProperties>
</WebElementEntity>
