<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkout_defaultDeliveryChargeFREE</name>
   <tag></tag>
   <elementGuidId>517e1c4e-966e-49f8-90ea-df36ea081d99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@qa='delivCharge']/span/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@qa='delivCharge']/span/strong</value>
   </webElementProperties>
</WebElementEntity>
