<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkout_DeliveryOptionsHeading</name>
   <tag></tag>
   <elementGuidId>a4662534-45ae-4fad-bf26-5d6db04bda66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@qa='chooseSlotTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@qa='chooseSlotTitle']</value>
   </webElementProperties>
</WebElementEntity>
