<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkout_OrderSummary_SettleBigBasketBalance</name>
   <tag></tag>
   <elementGuidId>fb96cbfa-7fb0-47cf-8489-e4215dc8e3ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//td[@class='text-right'][@qa='walletBalCKO']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td[@class='text-right'][@qa='walletBalCKO']</value>
   </webElementProperties>
</WebElementEntity>
