<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkout_DefaultDeliveryOptionHeading</name>
   <tag></tag>
   <elementGuidId>3ca655f4-7869-45f8-a16c-1b0a3cc99f0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//strong[@class='ng-scope']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//strong[@class='ng-scope']/span</value>
   </webElementProperties>
</WebElementEntity>
