<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>xPath_PrecedingInvoiceNumber</name>
   <tag></tag>
   <elementGuidId>5734f71a-8b2e-4696-afc7-0ee73b011ba5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//td[2]/a/span[text()=&quot;${Invoice_nbr}&quot;]/preceding::td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td[2]/a/span[text()=&quot;${Invoice_nbr}&quot;]/preceding::td</value>
   </webElementProperties>
</WebElementEntity>
