<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Delivery AddressNivedita S</name>
   <tag></tag>
   <elementGuidId>2747015c-308a-466c-ba51-2098ec17ff12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dynamicDirective']/information/section/my-order-list/div/section/div[2]/div/div[3]/div/my-order/div/div[2]/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>delivery-address</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delivery AddressNivedita Singh 9980921105 Bangalore 560034 9980921105</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dynamicDirective&quot;)/information[@class=&quot;ng-scope ng-isolate-scope&quot;]/section[@class=&quot;non-linear row custom-component&quot;]/my-order-list[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;my-order-page&quot;]/section[@class=&quot;row custom-component product-deck sticky-parent regular&quot;]/div[@class=&quot;col-md-9 wid-fix clearfix pl-wrap&quot;]/div[1]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;order-wrapper&quot;]/my-order[@class=&quot;ng-isolate-scope&quot;]/div[1]/div[@class=&quot;dropdown-content-wrapper ng-scope&quot;]/div[@class=&quot;dropdown-content padding-20 flex flex-vertical font12 stretch border&quot;]/div[@class=&quot;other-info flex align-self-stretch stretch flex-responsive clr-979797&quot;]/div[@class=&quot;delivery-address&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='dynamicDirective']/information/section/my-order-list/div/section/div[2]/div/div[3]/div/my-order/div/div[2]/div/div[2]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mon 18 Feb 2019, 09:12 am'])[1]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//my-order/div/div[2]/div/div[2]/div</value>
   </webElementXpaths>
</WebElementEntity>
