<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BigBasketLogo</name>
   <tag></tag>
   <elementGuidId>957fa163-3693-42ec-9de0-52325e7be854</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id=\'st-trigger-effects\']/a[@title=\'Bigbasket\']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id=\'st-trigger-effects\']/a[@title=\'Bigbasket\']</value>
   </webElementProperties>
</WebElementEntity>
