<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ItemCount</name>
   <tag></tag>
   <elementGuidId>84d1d872-2c47-4876-97ac-b8055543c6c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='my-basket-btn']/div/p[contains(.,'items')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='my-basket-btn']/div/p[contains(.,'items')]</value>
   </webElementProperties>
</WebElementEntity>
